title: Emryk™ - Technology That Heals
description: >-
  AI Healing Platforms for Cognitive Assistance
theme: minima
plugins:
  - jekyll-feed

# Exclude these files from production build
exclude:
  - Gemfile
  - Gemfile.lock
  - plan.md

# Minima configuration
minima:
  skin: classic
  social_links:
    email: info@emryk.com
