# Site settings
title: Emryk
tagline: The hearing aid for the mind
email: info@emryk.com
description: >-
  We empower brain injury survivors and neurodiverse individuals with BrainAmp™ Cognitive Amplifiers
  and BrainAmpCamps™ healing spaces that restore cognitive independence and rebuild lives.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://emryk.com"
twitter_username: emryk
github_username: emryk

# Build settings
markdown: kramdown
permalink: /:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom settings
logo: /assets/images/emryk-logo.png
copyright: "© 2025 Emryk™ - Licensed under CC BY 4.0"

# Navigation
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Our Approach
    url: /approach/
  - title: Contact
    url: /contact/

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "default"
